### ISSUE TITLE
Define API documentation

### ISSUE THREAD

**Issue by martinero17** [i-on-project/teams#11]

**Comment by afonsoamachado** [comment]
- [ ] review actions on Teacher APP (e.g. repo, team)

**Comment by afonsoamachado** [comment]
- [ ] review actions on Teacher APP (e.g. repo, team)
- [ ] Tag and delivery have no file.
- [ ] Link tag "/api/orgs/{orgId}/classrooms/{classId}/teams/{teamId}/repos/{repoId}/tags{tagName}" (pudemos usar o nome?)
- [ ] Check anchors
- [ ] verify all links between resources
